### PR TITLE
Improved error handling

### PR DESCRIPTION
**Pull request by ttjiaa**
This implements improvements in error handling that was done in Traefik.
- https://github.com/containous/traefik/pull/2702
- https://github.com/containous/traefik/pull/2825

### CODE REVIEW

**Comment by seriousben** [comment]
Thanks @ttjiaa

**Comment by felipenoris** [comment]
Hello, can this be merged?

**Comment by cihangir** [comment]
Thanks for sending the patches to us as well!

**Comment by ttjiaa** [comment]
@cihangir Will you be looking to have this merged?

**Comment by dsamarin** [comment]
@ttjiaa If you were to merge this into ttjia/websocketproxy master I would happily switch over. At least for me, 3 months is a good indication that this pull request is just going to sit indefinitely. Plus it's a dead simple library that just needed a little love.

**Comment by cihangir** [comment]
Sorry for making this PR wait a lot. Thanks again for updating it.

**Pull request merged**
